version: '2'
services:
  db:
    image: postgres

  mail-server:
    build:
      context: .
      dockerfile: Dockerfile-mail-server
    ports:
      - "7025:7025"
      - "7080:7080"

  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mail-server
