version: '2'
services:
  api:
    extends:
      file: docker-compose/common.yml
      service: api
    depends_on:
      - db
      - mail_server
      - rocketchat

  db:
    image: postgres

  mail_server:
    extends:
      file: docker-compose/common.yml
      service: mail_server

  rocketchat:
      image: rocketchat/rocket.chat:latest
      restart: unless-stopped
      volumes:
        - ./data/uploads:/app/uploads
      environment:
        - PORT=3002
        - ROOT_URL=http://localhost:3002
        - MONGO_URL=mongodb://mongo:27017/rocketchat
        - MONGO_OPLOG_URL=mongodb://mongo:27017/local
        - MAIL_URL=smtp://smtp.email
        - ADMIN_USERNAME=admin
        - ADMIN_PASS=admin
        - ADMIN_EMAIL=admin@zanza.com
      depends_on:
        - mongo
      ports:
        - 3002:3002
      labels:
        - "traefik.backend=rocketchat"
        - "traefik.frontend.rule=Host: your.domain.tld"

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

#  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
#  hubot:
#    image: rocketchat/hubot-rocketchat:latest
#    restart: unless-stopped
#    environment:
#      - ROCKETCHAT_URL=rocketchat:3002
#      - ROCKETCHAT_ROOM=GENERAL
#      - ROCKETCHAT_USER=bot
#      - ROCKETCHAT_PASSWORD=botpassword
#      - BOT_NAME=bot
#  # you can add more scripts as you'd like here, they need to be installable by npm
#      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
#    depends_on:
#      - rocketchat
#    labels:
#      - "traefik.enable=false"
#    volumes:
#      - ./scripts:/home/hubot/scripts
#  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
#    ports:
#      - 3001:8080

networks:
  default:
    external:
      name: zanza
