version: '2'
services:
  db:
    image: postgres

  mail_server:
    build:
      context: ../
      dockerfile: Dockerfile-mail-server
    ports:
      - "7025:7025"
      - "7080:7080"

  api:
    build: ../
    volumes:
      - ../src:/app
    ports:
      - "3000:3000"
      - "1234:1234"
    environment:
      - ROCKETCHAT_URL=http://rocketchat:3002
      - ROCKETCHAT_ADMIN_USER=admin
      - ROCKETCHAT_ADMIN_PASS=admin
      - APP_URL=http://0.0.0.0:8080

    command: /usr/local/bin/wait-for-it.sh db:5432 -s -- /usr/local/bin/startup-dev.sh
