require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JobsController, type: :controller do
  before(:each) do
    login_user
  end

  describe 'get#index' do
    it 'should return a list of all jobs' do
      3.times { create(:job, user: @user) }
      get :index
      expect(data.length).to eq 3
    end

    it 'should only return non-deleted jobs' do
      jobs = (0...3).collect { create(:job, user: @user) }
      jobs[0].destroy
      get :index
      expect(data.length).to eq 2
    end

    it 'should return a list of jobs created by a user when user_id is supplied' do
      3.times { create(:job, user: @user) }
      login_another_user
      create(:job, user: @user)
      get :index,
          params: { user_id: @user.id }
      expect(data.length).to eq 1
    end
  end

  describe 'get#show' do
    it 'should return a single job' do
      job = create(:job, user: @user)

      get :show,
          params: { id: job.id }

      expect(data['id']).to eq job.id
    end
  end

  describe 'post#create' do
    it 'should create a job' do
      job_attr = attributes_for(:job)

      post :create,
           params: job_attr

      expect(response).to have_http_status(:created)
      expect(data['id']).to be_truthy
      expect(data['title']).to eq job_attr[:title]
      expect(data['text']).to eq job_attr[:text]
      expect(data['user_id']).to eq @user.id
      expect(data['tag_list']).to eq job_attr[:tag_list]
      expect(data['per_diem']['min']).to eq job_attr[:per_diem][:min].to_s
      expect(data['per_diem']['max']).to eq job_attr[:per_diem][:max].to_s
      expect(data['closed_at']).to be_falsey
    end

    it 'should require a title to be created' do
      job_attr = attributes_for(:job)
      job_attr.delete(:title)

      post :create,
           params: job_attr

      expect(response).to have_http_status(:unprocessable_entity)
    end
  end

  describe 'patch#update' do
    it 'should update the job details belonging to a user' do
      job = create(:job, user: @user)
      new_job_attr = attributes_for(:job)

      patch :update,
            params: new_job_attr.merge(id: job.id)

      expect(response).to have_http_status(:ok)
      expect(data['id']).to eq(job.id)
      expect(data['title']).to eq new_job_attr[:title]
      expect(data['text']).to eq new_job_attr[:text]
      expect(data['tag_list']).to eq new_job_attr[:tag_list]
      expect(data['per_diem']['min']).to eq new_job_attr[:per_diem][:min].to_s
      expect(data['per_diem']['max']).to eq new_job_attr[:per_diem][:max].to_s
    end

    it 'should return an error if trying to update another users job' do
      job = create(:job, user: @user)
      login_another_user
      new_job_attr = attributes_for(:job)

      patch :update,
            params: new_job_attr.merge(id: job.id)

      expect(response).to have_http_status(:not_found)
    end
  end

  describe 'delete#destroy' do
    it 'should soft delete the job' do
      job = create(:job, user: @user)

      delete :destroy,
             params: { id: job.id }

      expect { Job.find(job.id) }.to raise_error(ActiveRecord::RecordNotFound)
      expect(Job.only_deleted.find(job.id)).to be_truthy
    end

    it 'should not delete another users job' do
      job = create(:job, user: @user)

      login_user

      delete :destroy,
             params: { id: job.id }

      expect(response).to have_http_status(:not_found)
    end
  end
end
