AllCops:
  Excludes:
    - db/schema.rb
    - db/migrate/20170331102531_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
    - db/migrate/20170331102535_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
    - db/migrate/20170331102535_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
  DisplayCopNames: true
Documentation:
    Enabled: false
Metrics/LineLength:
  Max: 120
ClassLength:
  Max: 250
Metrics/BlockLength:
  CountComments: false
  Max: 100000000
  ExcludedMethods: []
