source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end
# load any env variables before other gems are loaded
gem 'dotenv-rails', require: 'dotenv/rails-now'
# tagging
gem 'acts-as-taggable-on', '~> 4.0'
# soft deletes models
gem 'acts_as_paranoid'
# union between database queries
gem 'active_record_union'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# handles money and currency
gem 'money-rails', '~>1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
gem 'devise_token_auth'
gem 'rack-cors'
gem 'rocketchat'
gem 'stripe'
gem 'tzinfo-data'

group :development, :test do
  gem 'awesome_print', require: 'ap'
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'json_spec'
  gem 'rspec-rails'
  gem 'simplecov', require: false
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'rubocop', require: false
  # Spring speeds up development by keeping your application running in the background
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
